routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','IndexController@index');
Route::post('/mail_send','IndexController@mailSend');
Route::post('/reuqest_kredo','IndexController@kredo_request');


Auth::routes();

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
    Route::resource('filiallar' ,'FilalController');
    Route::resource('services' ,'ServicesController');
    Route::resource('about' ,'AboutController');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

resources/views/admin/filiallar/create.blade.php
@extends('layouts.static')
@section('content')
<!-- Horizontal Layout -->
<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        <h2>
        Filial əlavə et
        </h2>
      </div>
    </div>
  </div>
</div>

<div class="row clearfix" style="padding-bottom:50px;">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <form class="form-horizontal" action="{{ route('filiallar.store') }}" method="POST" enctype="multipart/form-data">
      {{ csrf_field() }}

      <div class="tab-content" style="margin-top:50px;">
           <div class="col-md-12 clearfix" style="padding:0 50px;">
               <div class="col-md-12" style="padding-top: 25px;">
                <p>
                  <b>Filial adı</b>
                </p>
                <input type="text"  class="form-control" name="filial_name" placeholder="Filial adını daxil edin" required>
              </div>

              <div class="col-md-6" style="padding-top: 25px;">
               <p>
                 <b>Filial Kordinatı (x) </b>
               </p>
               <input type="number"  class="form-control" name="filial_cordinat_x" placeholder="Filial Kordinatını (x) qeyd edin" required step="0.00000000000001">
             </div>
             <div class="col-md-6" style="padding-top: 25px;">
              <p>
                <b>Filial Kordinatı (y) </b>
              </p>
              <input type="number"  class="form-control" name="filial_cordinat_y" placeholder="Filial Kordinatını (y) qeyd edin" required step="0.00000000000001">
            </div>
            <div class="col-md-6" style="padding-top: 25px;">
             <p>
               <b>Filialın Ünvanı </b>
             </p>
             <input type="text"  class="form-control" name="filial_address" placeholder="Filialın Ünvanını qeyd edin" required >
           </div>
           <div class="col-md-6" style="padding-top: 25px;">
            <p>
              <b>Əlaqə Nömrəsi </b>
            </p>
            <input type="text"  class="form-control" name="filial_number" placeholder="Əlaqə Nömrəsini qeyd edin" required >
          </div>
            <!-- <div class="col-md-12" style="padding-top: 25px;">
             <p>
               <b>Filial Haqqında Qısa Məlumat </b>
             </p>
             <textarea   class="form-control" name="filial_about"  required></textarea>
           </div> -->
           <div class="col-md-12" style="padding-top: 25px;">

                 <button type="submit" name="button" class="btn btn-success ">Yarat</button>

           </div>
         </div>

    </form>
  </div>
</div>
<!-- #END# Horizontal Layout -->

@endsection

resources/views/admin/filiallar/edit.blade.php
@extends('layouts.static')
@section('content')
<!-- Horizontal Layout -->
<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        <h2>

        </h2>
      </div>
    </div>
  </div>
</div>
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

    <div>
      <form class="form-horizontal" action="{{ route('filiallar.update', $filial->id) }}" method="POST" enctype="multipart/form-data">
        {{ csrf_field() }}
         <input type="hidden" name="_method" value="PATCH">

         <div class="tab-content" style="margin-top:50px;">
              <div class="col-md-12 clearfix" style="padding:0 50px;">
                  <div class="col-md-12" style="padding-top: 25px;">
                   <p>
                     <b>Filial adı</b>
                   </p>
                   <input type="text"  class="form-control" name="filial_name" value="{{$filial->filial_name}}" required>
                 </div>

                 <div class="col-md-6" style="padding-top: 25px;">
                  <p>
                    <b>Filial Kordinatı (x) </b>
                  </p>
                  <input type="number"  class="form-control" name="filial_cordinat_x" value="{{$filial->filial_cordinat_x}}" required step="0.00000000000000000001">
                </div>
                <div class="col-md-6" style="padding-top: 25px;">
                 <p>
                   <b>Filial Kordinatı (y) </b>
                 </p>
                 <input type="number"  class="form-control" name="filial_cordinat_y" value="{{$filial->filial_cordinat_y}}" required step="0.00000000000000000001">
               </div>
               <div class="col-md-6" style="padding-top: 25px;">
                <p>
                  <b>Filialın Ünvanı </b>
                </p>
                <input type="text"  class="form-control" name="filial_address" value="{{$filial->filial_address}}" required >
              </div>
              <div class="col-md-6" style="padding-top: 25px;">
               <p>
                 <b>Əlaqə Nömrəsi </b>
               </p>
               <input type="text"  class="form-control" name="filial_number" value="{{$filial->filial_number}}" required >
             </div>
              <div class="col-md-12" style="padding-top: 25px;">

                    <button type="submit" name="button" class="btn btn-success ">Yarat</button>

              </div>
            </div>

       </form>
     </div>
      </form>
  </div>
</div>

@endsection

resources/views/admin/filiallar/index.blade.php
@extends('layouts.static')
@section('content')
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            @if(Session::has('mesaj'))
            <div class="alert alert-success alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                {{ Session::get('mesaj') }}
            </div>
            @endif
            <div class="header">
                <h2>
                <a href="{{ route('filiallar.create') }}"><button type="button" class="btn btn-success btn-circle waves-effect waves-circle waves-float">
                    <i class="material-icons">add</i>
                </button></a>
            </div>
            <div class="body table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                          <th>ID</th>
                        <th>Filial Adı</th>
                        <th>Filial kordinatı (x)</th>
                        <th>Filial kordinatı (y)</th>
                        <th>Filialın Ünvanı</th>
                        <th>Filialın Əlaqə Nömrəsi (y)</th>
                            <th><span class="text-danger">Sil</span> / <span class="text-success">Redaktə et</span></th>
                        </tr>
                    </thead>
                    <tbody>
                       @foreach($filiallar as $filial)
                        <tr>
                            <td>{{ $filial->id }}</td>
                            <td>{{ $filial->filial_name }}</td>
                            <td>{{ $filial->filial_cordinat_x }}</td>
                            <td>{{ $filial->filial_cordinat_y }}</td>
                            <td>{{ $filial->filial_address }}</td>
                            <td>{{ $filial->filial_number }}</td>
                            <td>
                                <form action="{{ route('filiallar.destroy', $filial->id) }}" method="post" style="display: initial;">
                                    {{ csrf_field() }}
                                    <input type="hidden" name="_method" value="DELETE">
                                    <input type="submit" value="Sil" class="btn btn-danger">
                                </form>
                                <a href="{{ route('filiallar.edit', $filial->id) }}" class="btn-success btn">Redaktə et</a>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
<!-- #END# Hover Rows -->

@endsection