routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','IndexController@index');
Route::post('/mail_send','IndexController@mailSend');
Route::post('/reuqest_kredo','IndexController@kredo_request');


Auth::routes();

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
    Route::resource('filiallar' ,'FilalController');
    Route::resource('services' ,'ServicesController');
    Route::resource('about' ,'AboutController');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

app/About.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class About extends Model
{
  protected $table = 'about';
protected $primaryKey = 'id';
public $timestamps = false;
protected $fillable = [

  'id','about'
];


}

app/Http/Controllers/AboutController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\About;
class AboutController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
      $haqq = About::first();
        return view('admin.about.index',compact('haqq'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('admin.about.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        About::create([
          'about'=>$request['about'],
        ]);
        return redirect('/admin/about');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $about = About::find($id);
        return view('admin.about.edit',compact('about'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
      $about = About::find($id);

      $about->update(['about'=>$request['about'],]);
        return redirect('/admin/about');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
      $about = About::find($id);
      $about->delete();
        return redirect('/admin/about');
    }
}

resources/views/admin/about/create.blade.php
@extends('layouts.static')
@section('content')

<!-- Horizontal Layout -->
<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        <h2>
        Haqqmızda
        </h2>
      </div>
    </div>
  </div>
</div>

<div class="row clearfix" style="padding-bottom:50px;">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <form class="form-horizontal" action="{{ route('about.store') }}" method="POST" enctype="multipart/form-data">
      {{ csrf_field() }}

      <div class="tab-content" style="margin-top:50px;">
           <div class="col-md-12 clearfix" style="padding:0 50px;">


            <div class="col-md-12" style="padding-top: 25px;">
             <p>
               <b>Haqqmızda </b>
             </p>
             <textarea   class="form-control" name="about"  required id='about'></textarea>
           </div>
           <div class="col-md-12" style="padding-top: 25px;">

                 <button type="submit" name="button" class="btn btn-success ">Yarat</button>

           </div>
         </div>

    </form>
  </div>
</div>
    <script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.replace( 'about' );
    </script>
<!-- #END# Horizontal Layout -->

@endsection

resources/views/admin/about/edit.blade.php
@extends('layouts.static')
@section('content')
<!-- Horizontal Layout -->
<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        <h2>

        </h2>
      </div>
    </div>
  </div>
</div>
<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

    <div>
      <form class="form-horizontal" action="{{ route('about.update', $about->id) }}" method="POST" enctype="multipart/form-data">
        {{ csrf_field() }}
         <input type="hidden" name="_method" value="PATCH">

         <div class="tab-content" style="margin-top:50px;">
              <div class="col-md-12 clearfix" style="padding:0 50px;">
                <div class="tab-content" style="margin-top:50px;">
                     <div class="col-md-12 clearfix" style="padding:0 50px;">


                      <div class="col-md-12" style="padding-top: 25px;">
                       <p>
                         <b>Haqqmızda </b>
                       </p>
                       <textarea   class="form-control" name="about"  required id='about'>{{$about->about}}</textarea>
                     </div>
                     <div class="col-md-12" style="padding-top: 25px;">

                           <button type="submit" name="button" class="btn btn-success ">Yarat</button>

                     </div>
                   </div>

              </form>
            </div>
          </div>
        </div>
              <script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
              <script>
                  CKEDITOR.replace( 'about' );
              </script>
          <!-- #END# Horizontal Layout -->

@endsection

resources/views/admin/about/index.blade.php
@extends('layouts.static')
@section('content')
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            @if(Session::has('mesaj'))
            <div class="alert alert-success alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                {{ Session::get('mesaj') }}
            </div>
            @endif
            <div class="header">
                <h2>
                  @if(!isset($haqq->about))
                <a href="{{ route('about.create') }}"><button type="button" class="btn btn-success btn-circle waves-effect waves-circle waves-float">
                    <i class="material-icons">add</i>
                </button></a>
                @endif
            </div>
            <div class="body table-responsive">
              <div class="col-md-12" style="padding-top: 25px;">
               <p>
                 <b>Haqqmızda </b>
               </p>
               <textarea   class="form-control" name="about"   id='about' readonly>@if(isset($haqq->about)){{$haqq->about}}@endif</textarea>
             </div>
             <div class="col-md-12">

              {{--  <form action="{{ route('about.destroy', $haqq->id) }}" method="post" style="display: initial;">
                    {{ csrf_field() }}
                    <input type="hidden" name="_method" value="DELETE">
                    <input type="submit" value="Sil" class="btn btn-danger">
                </form>--}}
                @if(isset($haqq->about))
                <a href="{{ route('about.edit', $haqq->id) }}" class="btn-success btn">Redaktə et</a>
                @endif
              </div>

            </div>
        </div>
    </div>
</div>
<!-- #END# Hover Rows -->
<script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
<script>
    CKEDITOR.replace( 'about' );
</script>
@endsection