routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/','IndexController@index');
Route::post('/mail_send','IndexController@mailSend');
Route::post('/reuqest_kredo','IndexController@kredo_request');


Auth::routes();

Route::group(['prefix' => 'admin', 'middleware' => 'auth'], function () {
    Route::resource('filiallar' ,'FilalController');
    Route::resource('services' ,'ServicesController');
    Route::resource('about' ,'AboutController');
});

Auth::routes();

Route::get('/home', 'HomeController@index');

app/Xidmet.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Xidmet extends Model
{
  protected $table = 'xidmet';
  protected $primaryKey = 'id';
  public $timestamps = false;
  protected $fillable = [
      'xidmet_name',
      'xidmet_icon',
      'xidmet_text',
  ];


}

resources/views/admin/xidmet/create.blade.php
@extends('layouts.static')
@section('content')
<!-- Horizontal Layout -->
<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        <h2>
          Xidmətlər
        </h2>
      </div>
    </div>
  </div>
</div>

<div class="row clearfix" style="padding-bottom:50px;">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <form class="form-horizontal" action="{{ route('services.store') }}" method="POST" enctype="multipart/form-data">
      {{ csrf_field() }}

      <div class="tab-content" style="margin-top:50px;">
        <div class="col-md-12 clearfix" >
            <div class="col-md-6" style="padding-top: 25px;">
             <p>
               <b>Xidmət adı</b>
             </p>
             <input type="text"  class="form-control" name="xidmet_name"  required>
           </div>
            <div class="col-md-6" style="padding-top: 25px;">
             <p>
               <b>Xidmətə aid icon</b>
             </p>
            <input type="file" class="form-control" name="xidmet_icon"  required>
           </div>
            <div class="col-md-12" style="padding-top: 25px;">
             <p>
               <b>Xidmətə mətni</b>
             </p>
            <textarea name="xidmet_text" rows="8" cols="80" id="article-ckeditor"></textarea>
           </div>

     </div>
      <div class="col-md-12" style="padding-top: 25px;">
        <div class="col-md-4">
            <button type="submit" name="button" class="btn btn-success ">Yarat</button>
        </div>
      </div>
    </form>
  </div>
</div>
<script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.replace( 'article-ckeditor' );
        CKEDITOR.replace( 'article-ckeditor1' );
    </script>
@endsection

resources/views/admin/xidmet/edit.blade.php
@extends('layouts.static')
@section('content')
<!-- Horizontal Layout -->
<div class="row clearfix">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <div class="card">
      <div class="header">
        <h2>
    Xidmətlər
        </h2>
      </div>
    </div>
  </div>
</div>

<div class="row clearfix" style="padding-bottom:50px;">
  <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
    <form class="form-horizontal" action="{{ route('services.update', $xidmet->id) }}" method="POST" enctype="multipart/form-data">
      {{ csrf_field() }}
      <input type="hidden" name="_method" value="PATCH">
      <div class="tab-content" style="margin-top:50px;">
        <div class="col-md-12 clearfix" >
            <div class="col-md-6" style="padding-top: 25px;">
             <p>
               <b>Xidmət adı</b>
             </p>
             <input type="text"  class="form-control" name="xidmet_name"  required value="{{$xidmet->xidmet_name}}">
           </div>
           <div class="col-md-6" style="padding-top: 25px;">
            <p>
              <b>Xidmətə aid icon</b>
            </p>
            <label for="img" style="width:120px;height:120px;"><img src="/uploads/{{$xidmet->xidmet_icon}}"  class="img-responsive"/></label>
           <input type="file" class="form-control" name="xidmet_icon"  id="img">
          </div>
           <div class="col-md-12" style="padding-top: 25px;">
            <p>
              <b>Xidmətə mətni</b>
            </p>
           <textarea name="xidmet_text" rows="8" cols="80" id="article-ckeditor">{{$xidmet->xidmet_text}}</textarea>
          </div>


     </div>
      <div class="col-md-12" style="padding-top: 25px;">
        <div class="col-md-4">
            <button type="submit" name="button" class="btn btn-success ">Yarat</button>
        </div>
      </div>
    </form>
  </div>
</div>
<script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
    <script>
        CKEDITOR.replace( 'article-ckeditor' );
        CKEDITOR.replace( 'article-ckeditor1' );
    </script>
@endsection

resources/views/admin/xidmet/index.blade.php
@extends('layouts.static')
@section('content')
<div class="row clearfix">
    <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
        <div class="card">
            @if(Session::has('mesaj'))
            <div class="alert alert-success alert-dismissable">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">×</span></button>
                {{ Session::get('mesaj') }}
            </div>
            @endif
            <div class="header">
                <h2>
                <a href="{{ route('services.create') }}"><button type="button" class="btn btn-success btn-circle waves-effect waves-circle waves-float">
                    <i class="material-icons">add</i>
                </button></a>
            </div>
            <div class="body table-responsive">
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th>ID</th>
                            <th>Xidmət Adı</th>
                            <th><span class="text-danger">Sil</span> / <span class="text-success">Redaktə et</span></th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach($xidmetler as $xidmet)
                        <tr>
                            <td>{{ $xidmet->id }}</td>
                          <td>{{ $xidmet->xidmet_name }}</td>
                            <td>
                                <form action="{{ route('services.destroy', $xidmet->id) }}" method="post" style="display: initial;">
                                    {{ csrf_field() }}
                                    <input type="hidden" name="_method" value="DELETE">
                                    <input type="submit" value="Sil" class="btn btn-danger">
                                </form>
                                <a href="{{ route('services.edit', $xidmet->id) }}" class="btn-success btn">Redaktə et</a>
                            </td>
                        </tr>
                        @endforeach
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

@endsection